inc:
  title:        "Whiskaroo"
  subtitle:     "Boozy musings from the good folks at Taster's Club"
  cover_image:  whiskaroo_hero.jpg
  logo:         logo_bright.png
  company:      Taster's Club
  url:          http://www.tastersclub.com/
  facebook:     tastersclub
  twitter:      tastersclub
  gplus:        '101183822199340201470'
  about_link:   https://www.tastersclub.com/
  product_link: http://www.tastersclub.com
  tagline:      ""
  disqus:
    shortname:  false
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false  
  analytics:
    google: 
      id:       false
  google_font: 'Droid+Sans:400,700'
url:         http://incorporated.sendtoinc.com
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     [vendor]
timezone:    nil
future:      false
show_drafts: nil
limit_posts: 0
pygments:    true
relative_permalinks: true
permalink:     pretty
paginate_path: 'page:num'
paginate: 10
markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile
excerpt_separator: "<!-- more -->"
safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
rdiscount:
  extensions: []
redcarpet:
  extensions: []
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
redcloth:
  hard_breaks: true
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false